// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetCurrentURL() {
  return window['go']['main']['App']['GetCurrentURL']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function IsPlaying() {
  return window['go']['main']['App']['IsPlaying']();
}

export function PlayChannel(arg1) {
  return window['go']['main']['App']['PlayChannel'](arg1);
}

export function ReloadPlaylist() {
  return window['go']['main']['App']['ReloadPlaylist']();
}

export function SearchChannels(arg1) {
  return window['go']['main']['App']['SearchChannels'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function StopPlayback() {
  return window['go']['main']['App']['StopPlayback']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
