// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {playlist} from '../models';

export function GetCategories():Promise<Array<string>>;

export function GetChannels():Promise<Array<playlist.Channel>>;

export function GetCurrentURL():Promise<string>;

export function GetVolume():Promise<number>;

export function IsPlaying():Promise<boolean>;

export function PlayChannel(arg1:string):Promise<void>;

export function ReloadPlaylist():Promise<void>;

export function SearchChannels(arg1:string):Promise<Array<playlist.Channel>>;

export function SetVolume(arg1:number):Promise<void>;

export function StopPlayback():Promise<void>;

export function TogglePause():Promise<void>;
